apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: web-server
          image: $IMAGE
          ports:
            - containerPort: 8080
          env:
          - name: API_SERVER
            value: http://$BE_SERVICE_NAME:8082
  ---

  apiVersion: v1
  kind: Service
  metadata:
    name: fe-service
  spec:
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
    selector:
      app: frontend
    type: LoadBalancer
